const products = [
  { name: 'Berry Blush Cake', price: '₹1,450', rating: '4.9', reviews: 184, tag: 'BESTSELLER', img: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=700&q=85' },
  { name: 'Classic Fudge Brownies', price: '₹550', rating: '4.8', reviews: 96, tag: 'FRESH TODAY', img: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=700&q=85' },
  { name: 'Lemon Cloud Cake', price: '₹1,250', rating: '5.0', reviews: 73, tag: 'FAVOURITE', img: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&w=700&q=85' },
  { name: 'Sunday Cookie Box', price: '₹690', rating: '4.9', reviews: 122, tag: 'GIFTABLE', img: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=700&q=85' }
];
let bag = [], selected = products[0], reviewIndex = 0;
const grid = document.querySelector('#productGrid'), bagPanel = document.querySelector('#bagPanel'), overlay = document.querySelector('#overlay');
function renderProducts() { grid.innerHTML = products.map((p, i) => `<article class="product-card"><div class="product-image"><img src="${p.img}" alt="${p.name}"/><span class="tag">${p.tag}</span><button class="quick-add" data-add="${i}" aria-label="Add ${p.name}">+</button></div><div class="product-info"><span class="price">${p.price}</span><h3>${p.name}</h3><div class="rating"><b>★★★★★</b> ${p.rating} · <button class="review-link" data-review="${i}">${p.reviews} photo reviews</button></div></div></article>`).join(''); }
function renderBag() { document.querySelector('#bagCount').textContent = bag.length; document.querySelector('#bagItems').innerHTML = bag.length ? bag.map((p,i) => `<div class="bag-item"><img src="${p.img}" alt="${p.name}"/><div><b>${p.name}</b><br><small>${p.price} · Customise before checkout</small><br><button class="review-link" data-remove="${i}">Remove</button></div></div>`).join('') : '<p class="empty">Your bag is waiting for something delicious.</p>'; }
function toggleBag(show) { bagPanel.classList.toggle('open', show); overlay.classList.toggle('open', show); }
function openOrder(product) { selected = product; document.querySelector('#orderProduct').textContent = `${product.name} · ${product.price || 'Made to order'}`; document.querySelector('#orderPhoto').style.backgroundImage = `url('${product.img || products[0].img}')`; document.querySelector('#orderDialog').showModal(); }
grid.addEventListener('click', e => { const i = e.target.dataset.add ?? e.target.dataset.review; if (i === undefined) return; const p = products[i]; if (e.target.dataset.add !== undefined) { bag.push(p); renderBag(); toggleBag(true); } else openOrder(p); });
document.querySelector('#bagButton').onclick = () => toggleBag(true); overlay.onclick = () => toggleBag(false); document.querySelectorAll('[data-close]').forEach(b => b.onclick = () => { toggleBag(false); document.querySelector('#orderDialog').close(); });
document.querySelector('#bagItems').onclick = e => { if (e.target.dataset.remove !== undefined) { bag.splice(e.target.dataset.remove, 1); renderBag(); } };
document.querySelector('#checkoutButton').onclick = () => openOrder(bag[0] || products[0]);
document.querySelectorAll('[data-product]').forEach(b => b.onclick = () => openOrder({ name: b.dataset.product, price: 'Made to order', img: 'https://images.unsplash.com/photo-1535141192574-5d4897c12636?auto=format&fit=crop&w=700&q=85' }));
document.querySelector('#orderForm').addEventListener('submit', e => { e.preventDefault(); const d = new FormData(e.target); const text = `Hello Mom's Bakkery! I'd like to order *${selected.name}* (${selected.price || 'Made to order'}).%0A%0A*Name:* ${d.get('name')}%0A*Phone:* ${d.get('phone')}%0A*Address:* ${d.get('address')}%0A*Sweet details:* ${d.get('notes') || 'None'}%0A*Payment:* ${d.get('payment')}%0A%0APlease confirm my order and share the payment details.`; window.open(`https://wa.me/919999999999?text=${text}`, '_blank'); });
const testimonials = [{quote:'The cake looked even more magical than the reference I sent. Everyone wanted a second slice — and the little handwritten note made me tear up!',name:'Meera Shah',meta:'Ordered a custom birthday cake',avatar:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=70',photo:'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=300&q=80'},{quote:'The brownies vanished before I could set them on the table. Perfectly fudgy, beautifully packed, and delivered right on time.',name:'Rhea Malhotra',meta:'Ordered the brownie box',avatar:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=100&q=70',photo:'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=300&q=80'}];
function renderReview(){const r=testimonials[reviewIndex];document.querySelector('#testimonial').innerHTML=`<div class="quote">“</div><blockquote>${r.quote}</blockquote><div class="reviewer"><img src="${r.avatar}" alt="${r.name}"/><span><b>${r.name}</b><br/><small>${r.meta} · <b>★★★★★</b></small></span></div><img class="review-photo" src="${r.photo}" alt="Photo from ${r.name}'s review"/>`;}
document.querySelector('#prevReview').onclick=()=>{reviewIndex=(reviewIndex+testimonials.length-1)%testimonials.length;renderReview()};document.querySelector('#nextReview').onclick=()=>{reviewIndex=(reviewIndex+1)%testimonials.length;renderReview()};renderProducts();renderBag();renderReview();
